version: '3.8'
services:
  database:
    image: postgres:12.2-alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 1GB

volumes:
  database-data: